[package]
name = "wgsl-preprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
preproc-core = { version = "0.1.0", path = "preproc-core" }
preproc-derive = { version = "0.1.0", path = "preproc-derive" }
